03_Web/Web_aclass/web_pjt/0422_django_pjt3/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

03_Web/Web_aclass/web_pjt/0422_django_pjt3/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    ]

03_Web/Web_aclass/web_pjt/0422_django_pjt3/django_pjt3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

03_Web/Web_aclass/web_pjt/0422_django_pjt3/accounts/models.py
from django.db import models

# Create your models here.

03_Web/Web_aclass/web_pjt/0422_django_pjt3/community/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=30)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

03_Web/Web_aclass/web_pjt/0422_django_pjt3/community/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    rank = forms.IntegerField(
        widget = forms.NumberInput(
            attrs={
                'min':'1',
                'max':'10',
            }
            )
        )
    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'content', 'rank']

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'placeholder': '댓글을 작성해주세요.',
                'rows': 3,
            }
            )
        )
    class Meta:
        model = Comment
        fields = ['content']

03_Web/Web_aclass/web_pjt/0422_django_pjt3/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            auth_login(request, authenticated_user)
            return redirect('community:index')
        else:
            messages.warning(request, '폼을 다시 확인 후 제출해주세요.')
    else:
        form = UserCreationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:index')
        else:
            messages.warning(request, '이름과 비밀번호를 다시 확인 후 제출해주세요.')
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('community:index')

03_Web/Web_aclass/web_pjt/0422_django_pjt3/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
def index(request):
    reviews = Review.objects.order_by('-rank')
    context = {
        'reviews': reviews
    }
    return render(request, 'community/review_list.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('community:detail', review.pk)
        else:
            messages.warning(request, '리뷰를 양식에 맞게 작성해주세요.')
    else:
        review_form = ReviewForm()
    context = {
        'review_form': review_form
    }
    return render(request, 'community/form.html', context)

def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm()
    context = {
        'review': review,
        'comment_form': comment_form
    }
    return render(request, 'community/review_detail.html', context)

@require_POST
@login_required
def delete(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        review.delete()
        return redirect('community:index')
    return redirect('community:detail', review.pk)

@login_required
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.user == review.user:
        if request.method == 'POST':
            review_form = ReviewForm(request.POST, instance=review)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.user = request.user
                review.save()
                return redirect('community:detail', review.pk)
            else:
                messages.warning(request, '리뷰를 양식에 맞게 작성해주세요.')
        else:
            review_form = ReviewForm(instance=review)
        context = {
            'review_form':review_form
        }
        return render(request, 'community/form.html', context)
    else:
        return redirect('community:detail', review.pk)

@require_POST
@login_required
def comment_create(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.review = review
        comment.save()
    return redirect('community:detail', review.pk)

@require_POST
@login_required
def comment_delete(request, review_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('community:detail', review_pk)

03_Web/Web_aclass/web_pjt/0422_django_pjt3/community/templates/community/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form review_form %}
        <div class="d-flex justify-content-end">
        {% if request.resolver_match.url_name == 'create' %}
            <button class="btn btn-danger">작성하기</button>
        {% else %}
            <button class="btn btn-danger">수정하기</button>
        {% endif %}
        </div>


    </form>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}

03_Web/Web_aclass/web_pjt/0422_django_pjt3/community/templates/community/review_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div class="card border-0">
    <div class="card-header text-white d-flex justify-content-between align-items-center">
      <h4>{{ review.movie_title }}<span class="badge badge-dark mx-3"><svg class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
</svg>{{ review.rank }}</span></h4>
    <!--게시글 수정 및 삭제 기능 -->
    {% if request.user == review.user %}
      <div class="btn-group" role="group">
        <a href="{% url 'community:update' review.pk %}"><button class="btn btn-dark mx-3 btn-sm" >수정</button></a>
        <form action="{% url 'community:delete' review.pk %}" method="POST">
          {% csrf_token %}
          <button class="btn btn-dark btn-sm" >삭제</button>
        </form>
      </div>
    {% endif %}
    </div>
    <div class="card-body bg-dark">
      <h5 class="card-title">{{ review.title }} <small>| 작성자 : {{ review.user.username }}</small></h5>
      <hr>
      <p class="card-text">{{ review.content | linebreaks }}</p>
      <hr>
      <!--댓글 보여주기 -->
      <h6>댓글</h6>
      {% for comment in review.comments.all %}
      <div class="input-group p-auto">
        <p class="mb-0 mr-3">{{ comment.user.username }}: {{ comment.content }}</p>
        <!--댓글 삭제 -->
        {% if request.user == comment.user %}
          <form class="form-inline" action="{% url 'community:comment_delete' review.pk comment.pk %}" method="POST" >
            {% csrf_token %}
            <div class="input-group-append">
              <button class="btn btn-danger btn-sm">삭제</button>
            </div>
          </form>
        {% endif %}
        </div>
        <hr>
      {% endfor %}
      <!-- 댓글 작성란 -->
      {% if request.user.is_authenticated %}
        <form class="" action="{% url 'community:comment_create' review.pk %}" method="POST">
          {% csrf_token %}
          {% bootstrap_form comment_form %}
          <button type="submit" class="btn btn-danger offset-10 col-2">댓글 작성</button>
        </form>
      {% endif %}
    </div>
    <div class="card-footer">
      <p class="text-white d-inline mx-3">Created at: {{ review.created_at }}</p>
      <p class="mb-0 text-white d-inline">Updated at: {{ review.updated_at }}</p>

    </div>
  </div>
  {% endblock %}


<!--

  <div class="card border-0">
    <div class="card-header text-white">
      <h4>{{ review.movie_title }}<span class="badge badge-dark mx-3"><svg class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
</svg>{{ review.rank }}</span></h4>
    </div>
    <div class="card-body bg-dark">
      <h5 class="card-title">{{ review.title }}</h5>
      <p class="card-text">{{ review.content | linebreaks }}</p>
      <hr>
      <h6>댓글</h6>
      {% for comment in review.comments.all %}
      <div class="input-group p-auto">
        <p class="mb-0 mr-3">{{ comment.user.username }}: {{ comment.content }}</p>

        {% if request.user == comment.user %}
          <form class="form-inline" action="{% url 'community:comment_delete' review.pk comment.pk %}" method="POST" >
            {% csrf_token %}
            <div class="input-group-append">
              <button class="btn btn-danger btn-sm">삭제</button>
            </div>
          </form>
        {% endif %}
        </div>
        <hr>
      {% endfor %}

      {% if request.user.is_authenticated %}
        <form class="" action="{% url 'community:comment_create' review.pk %}" method="POST">
          {% csrf_token %}
          {% bootstrap_form comment_form %}
          <button type="submit" class="btn btn-danger offset-10 col-2">댓글 작성</button>
        </form>
      {% endif %}
    </div>
    <div class="card-footer">
      <p class="text-white d-inline mx-3">Created at: {{ review.created_at }}</p>
      <p class="mb-0 text-white d-inline">Updated at: {{ review.updated_at }}</p> <br>

       {% if request.user == review.user %}
         <div class="btn-group" role="group">
          <a href="{% url 'community:update' review.pk %}"><button class="btn btn-dark mx-3 btn-sm" >수정</button></a>
          <form action="{% url 'community:delete' review.pk %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-dark btn-sm" >삭제</button>
          </form>
        </div>
        {% endif %}
    </div>
  </div>

-->

03_Web/Web_aclass/web_pjt/0422_django_pjt3/community/templates/community/review_list.html
{% extends 'base.html' %}

{% block content %}
<div class="mx-0">
<h1 class="mt-5 font-weight-bold">Popular on Netflex</h1>

<div class="container">
  <div class="row">
  {% for review in reviews %}
    <div class="card bg-dark col-3 my-2" style="width: 18rem; border: 10px black solid; border-radius: 25px;">
      <div class="card-body d-flex flex-column justify-content-between">
        <h5 class="card-title"><a href="{% url 'community:detail' review.pk %}" class="text-decoration-none text-light">{{ review.title|truncatechars:20 }}</a></h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ review.movie_title|truncatechars:15 }}</h6>
        <p class="card-text">{{ review.content|truncatechars:15 }}</p>
        <small>별점 : {{ review.rank }}</small>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
</div>
{% endblock %}

03_Web/Web_aclass/web_pjt/0422_django_pjt3/templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Netflex</title>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&family=Sunflower:wght@300;500;700&display=swap" rel="stylesheet">
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'community/css/base.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark d-flex align-items-center">
      <a class="navbar-brand ml-4" href="{% url 'community:index' %}"><p class="logo">Netflex</p></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'community:index' %}">홈</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'community:create' %}">리뷰 작성</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>